name: calorie_tracker
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  
  #localization
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0

  #view
  cupertino_icons: ^1.0.4
  flutter_svg: ^1.0.2
  badges: ^2.0.2
  flash: ^2.0.3+2
  modal_bottom_sheet: ^2.0.0

  
  #nav
  auto_route: ^3.2.1
  dio: ^4.0.4

  #state
  hooks_riverpod: ^1.0.3
  flutter_hooks: ^0.18.2
  
  #functional
  json_annotation: ^4.4.0
  freezed_annotation: ^1.1.0
  dartz: ^0.10.1
  uuid: ^3.0.5

  #firebase
  # firebase_core: ^1.11.0
  # firebase_messaging: ^11.2.5
  # firebase_crashlytics: ^2.4.5
  # firebase_analytics: ^9.0.5

  #device specific
  device_info_plus: ^3.2.1
  package_info_plus: ^1.3.0

  #persistance
  shared_preferences: ^2.0.12
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  path: ^1.8.0
  path_provider: ^2.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter

  auto_route_generator: ^3.2.1
  hive_generator: ^1.1.2
  lint: ^1.8.2
  build_runner: ^2.1.7
  freezed: ^1.1.1
  json_serializable: ^6.1.4

flutter:
  uses-material-design: true
  generate: true

  assets:
    # - assets/images/
    - assets/icons/
    - assets/config/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/Montserrat/Montserrat-Italic.ttf
          style: italic
        - asset: assets/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 700
        - asset: assets/fonts/Montserrat/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat/Montserrat-Medium.ttf
          weight: 500
        - asset: assets/fonts/Montserrat/Montserrat-Thin.ttf
          weight: 100

